name = "Create Convergence SMP"
author = "sarisman84, maam27"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d043a781ac5a13124bc1f01f4a1288b7246b5df287f1448637716ed20a17a107"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
