name = "Create Convergence SMP"
author = "sarisman84, maam27"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "248c276335f35d0b045088024dff456818f24a9b5c57e2ec3ee89f33a04a14cb"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
